services:
  app:
    environment:
      - PROJECT_PATH=/project/nycu_deep_learning_lab2
      - TZ=Asia/Taipei
    build:
      context: .
      target: prod
      # secrets:
      #   - GIT_AUTH_TOKEN
      args:
        - PROJECT_PATH=/project/nycu_deep_learning_lab2
        - TZ=Asia/Taipei
    shm_size: 8G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

# secrets:
#   GIT_AUTH_TOKEN:
#     environment: GIT_AUTH_TOKEN
