services:
  app:
    environment:
      - PROJECT_PATH=/project/nycu_deep_learning_lab2
      - TZ=Asia/Taipei
    build:
      context: ..
      target: dev
      # secrets:
      #   - GIT_AUTH_TOKEN
      args:
        - PROJECT_PATH=/project/nycu_deep_learning_lab2
        - TZ=Asia/Taipei
    volumes:
      - ..:/project/nycu_deep_learning_lab2:rw,cached
      - ${UV_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME}/.cache}/uv}:/root/.cache/uv:rw,z
    shm_size: 6G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

# secrets:
#   GIT_AUTH_TOKEN:
#     environment: GIT_AUTH_TOKEN
