name: release zip

on:
  push:
    paths-ignore:
      - "uv.lock"
      - "requirements.txt"
  workflow_run:
    workflows: ["Update requirements.txt on PR"]
    types:
      - completed  # As long as it's completed, we will run this job, no matter success or failure

jobs:
  zip-artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'skipped' }}
    env:
      LABNO: ${{ vars.LABNO }}
      STUID: ${{ vars.STUID }}
      NAME: ${{ vars.NAME }}
      ZIP_NAME: DL_Lab${{ vars.LABNO }}_${{ vars.STUID }}_${{ vars.NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Validate required variables
        run: |
          if [ -z "${LABNO}" ] || [ -z "${STUID}" ] || [ -z "${NAME}" ]; then
            echo "Error: LABNO, STUID, NAME aren't set!"
            exit 1
          fi

      - name: Create empty directories
        run: mkdir -p dataset/oxford-iiit-pet saved_models

      - name: Upload zip archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            dataset
            src
            saved_models
            requirements.txt